language: cpp

os:
  - linux
  - osx

arch:
  - amd64
  - arm64

env:
  matrix:
    - NODE_VERSION="10"
    - NODE_VERSION="12"
    - NODE_VERSION="16"

matrix:
  fast_finish: true

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - export CXX=g++
  - export CC=gcc
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8; fi
  - rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

install:
  - npm install --build-from-source

script:
  - npm run lint
  - npm run test-cov
  - node custom-prebuild-ci

after_success:
  - npm run coveralls
  - COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
